# Generated by Django 5.2.5 on 2025-09-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='games/')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=20)),
                ('prize', models.IntegerField()),
                ('teams', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='myproject.game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('settings', models.CharField(max_length=20)),
                ('tournaments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='myproject.tournament')),
            ],
        ),
    ]
