# Generated by Django 5.2.5 on 2025-10-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_tournament_end_date_tournament_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tournaments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='myproject.tournament'),
        ),
    ]
